[tool.poetry]
name = "antarctic-plots"
version = "0.0.4.2"
description = "Functions to automate Antarctic data visualization"
authors = ["mdtanker <matt.d.tankersley@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "antarctic_plots"}]
homepage = "https://antarctic-plots.readthedocs.io/en/latest/installation.html"
repository = "https://github.com/mdtanker/antarctic_plots"
documentation = "https://antarctic-plots.readthedocs.io/en/latest/api.html"
keywords = ["antarctica", "plotting", "pygmt", "cross-section", "bedmap", "bedmachine"]
exclude = ["antarctic_plots/tests", "docs"]

[tool.poetry.dependencies]
python = "~3.9"
pygmt = "0.7.0"
geopandas = "0.12.1"
conda-lock = "^1.2.1"
pandas = "^1.5.1"
pooch = {extras = ["progress"], version = "^1.6.0"}
verde = "^1.7.0"
xarray = {extras = ["io"], version = "^2022.10.0"}
pyproj = "^3.4.0"
matplotlib = "^3.6.1"
pyogrio = "^0.4.2"
rioxarray = "^0.12.4"
scipy = "^1.9.3"
numpy = "^1.23.4"
openpyxl = "^3.0.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
Flake8-pyproject = "^1.1.0.post0"
black = {extras = ["jupyter"], version = "^22.10.0"}
nbsphinx = "^0.8.9"
sphinx-gallery = "^0.11.1"
jupyter-book = "^0.13.1"
nbconvert = "<7"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 88

[tool.coverage.run]
branch = true
omit = [
    "*/tests/*",
    "**/__init__.py"
    ]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "earthdata: marks tests as requiring earthdata login info (deselect with '-m \"not earthdata\"')",
    "issue: mark tests with current issues (deselect with '-m \"not issues\"')",
    "working: marks tests which are working",
]